#!/usr/bin/env bash
# Builds a cursor theme whose default arrow is the current theme's own pencil.
#
# Pen mode wants the pointer to look like a pen. Shipping a cursor theme for that would
# mean shipping artwork that clashes with whatever the user already chose, and Hyprland's
# `setcursor` selects a *theme*, not a shape — the shape is picked by each client, and
# clients ask for `default`/`left_ptr`.
#
# So the theme is derived rather than drawn: a directory that inherits the user's theme
# and overrides only the arrow with that same theme's `pencil`. The pen cursor is then
# the user's own cursor art, in the user's own style, at whatever size they asked for.
#
# Usage: pen-cursor.sh <parent-theme>
# Prints the generated theme's name on success.
set -euo pipefail

parent="${1:-}"
[ -n "$parent" ] || { echo "usage: pen-cursor.sh <parent-theme>" >&2; exit 2; }

name="${parent}-pen"
out="${XDG_DATA_HOME:-$HOME/.local/share}/icons/${name}"

# Where the parent lives. Themes may sit in either tree; the user's own wins.
src=""
for base in "${XDG_DATA_HOME:-$HOME/.local/share}/icons" "$HOME/.icons" /usr/share/icons; do
    if [ -e "$base/$parent/cursors/pencil" ]; then
        src="$base/$parent/cursors"
        break
    fi
done

if [ -z "$src" ]; then
    echo "theme '$parent' has no pencil cursor" >&2
    exit 1
fi

mkdir -p "$out/cursors"
cat > "$out/index.theme" <<EOF
[Icon Theme]
Name=${name}
Comment=${parent} with a pen for a pointer, generated by illogical-impulse
Inherits=${parent}
EOF

# Only the shapes a client asks for when it wants "the pointer". Everything else — the
# I-beam over text, the resize arrows on a window edge — is inherited unchanged, because
# those still mean what they always meant with a pen in your hand.
for shape in default left_ptr arrow top_left_arrow; do
    cp -f "$src/pencil" "$out/cursors/$shape"
done

echo "$name"
